import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset=pd.read_csv('train.csv')
X=dataset.drop('Survived',axis=1)
Y=dataset['Survived']
Z=pd.read_csv('test.csv')
X.Fare=X.Fare.fillna(X.Fare.mean())
Z.Fare=Z.Fare.fillna(Z.Fare.mean())
X.Age=X.Age.fillna(X.Age.mean())
X.Embarked=X.Embarked.fillna(X.Embarked.mode()[0])
X.Cabin=X.Cabin.fillna("UK")
X['title']=X.Name.apply(lambda x:x.split('.')[0].split(',')[1].strip())
Z.Age=Z.Age.fillna(Z.Age.mean())
Z.Embarked=Z.Embarked.fillna(Z.Embarked.mode()[0])
Z.Cabin=Z.Cabin.fillna("UK")
Z['title']=Z.Name.apply(lambda x:x.split('.')[0].split(',')[1].strip())
X['repu']=X.Name.apply(lambda x:x.split(',')[0])
Z['repu']=Z.Name.apply(lambda x:x.split(',')[0])
#X['Nam']=X.Name.apply(lambda x:x.split('.')[1].strip())
#Z['Nam']=Z.Name.apply(lambda x:x.split('.')[1].strip())
X=X.drop('Name',axis=1)
Z=Z.drop('Name',axis=1)
X=X.drop('Ticket',axis=1)
Z=Z.drop('Ticket',axis=1)
X=X.drop('Cabin',axis=1)
Z=Z.drop('Cabin',axis=1)
from sklearn.preprocessing import LabelEncoder
labelEncoder_X=LabelEncoder()
X['Sex']=labelEncoder_X.fit_transform(X['Sex'])
Z['Sex']=labelEncoder_X.fit_transform(Z['Sex'])
X['title']=labelEncoder_X.fit_transform(X['title'])
Z['title']=labelEncoder_X.fit_transform(Z['title'])
X['Embarked']=labelEncoder_X.fit_transform(X['Embarked'])
Z['Embarked']=labelEncoder_X.fit_transform(Z['Embarked'])
X['repu']=labelEncoder_X.fit_transform(X['repu'])
Z['repu']=labelEncoder_X.fit_transform(Z['repu'])
#X['Nam']=labelEncoder_X.fit_transform(X['Nam'])
#Z['Nam']=labelEncoder_X.fit_transform(Z['Nam'])
#X['Cabin']=labelEncoder_X.fit_transform(X['Cabin'])
#Z['Cabin']=labelEncoder_X.fit_transform(Z['Cabin'])
#X['Ticket']=labelEncoder_X.fit_transform(X['Ticket'])
#Z['Ticket']=labelEncoder_X.fit_transform(Z['Ticket'])
#from sklearn.model_selection import train_test_split
#X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=1)
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=50,criterion='entropy',random_state=1)
classifier.fit(X,Y)
pred=classifier.predict(Z)
output=pd.DataFrame({'PassengerId':Z['PassengerId'],'Survived':pred})
output.to_csv('submission.csv', index=False)